#spring.application.name=getmyticket-backend
#spring.datasource.url=jdbc:mysql://localhost:3306/get_my_ticket
#spring.datasource.username=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#server.port=8000

pring.application.name=${SPRING_APPLICATION_NAME}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.database=${SPRING_JPA_DATABASE}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

springdoc.swagger-ui.tagsSorter=alpha

server.port=${SERVER_PORT:8080}

application.security.jwt.secret-key=${application.security.jwt.secret-key}
application.security.jwt.expiration=${application.security.jwt.expiration}
